# Generated by Django 5.0.7 on 2024-07-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_imageupload_delete_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
