# Generated by Django 5.0.7 on 2024-07-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_remove_imageupload_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='sex',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
