# Generated by Django 5.0.7 on 2024-07-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_doctorreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='name',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
