# Generated by Django 5.0.7 on 2024-07-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_alter_imageupload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreg',
            name='qual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
