# Generated by Django 5.0.7 on 2024-07-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_alter_doctorreg_qual'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
